name: Deploy Databricks Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Configure Databricks Auth
        run: |
          databricks auth login --host $DATABRICKS_HOST
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}

      - name: Deploy Bundle
        run: |
          databricks bundle deploy
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}